### ISSUE TITLE
[BUG] Rougelike Dungeons Crash

### ISSUE THREAD

**Issue by Diamondman121314** [magmafoundation/Magma#213]
**Describe the bug**
A clear and concise description of what the bug is:
Apparently after the update to the 1.12 branch yesterday adding Forge commands to help, I guess it caused an issue with Roguelike Dungeons: Fnar Edition. Looking at the commit and the crashlog, I'm assuming Magma would be the issue here.

**To Reproduce**
1. Load server all the way to after Spigot loads.

**Expected behavior**
Server to load fine, not crash at the last second.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Mod Name: Roguelike Dungeons: Fnar Edition
 - Mod Version: 2.1.3
 - Magma Version: 4695040
 - OS: Linux (don't know the details as I don't have access to that)

**Additional context**
[Crash Report](https://gist.github.com/Diamondman121314/12d01cc7e95a528b01c775c9ed7a6469)

**Comment by UeberallGebannt** [comment]
We need the crash log

**Comment by Diamondman121314** [comment]
On the bottom.

**Comment by kwright02** [comment]
Closing this as it is fixed.

**Comment by Diamondman121314** [comment]
May I asked where I can obtain this fix or has it not been uploaded yet? If so, that's fine, I'm just unsure.

**Comment by kwright02** [comment]
Hex marked it as fixed so i'm guessing that either the current latest version or the next one will have the fix.

**Comment by UeberallGebannt** [comment]
Please reopen as it is not fixed yet.

Crash: https://mclo.gs/Pcze1CQ
Crashreport: https://mclo.gs/ykDMHUQ

**Comment by SSKirillSS** [comment]
Can confirm. Forks of RD crash server too.

**Comment by kwright02** [comment]
Fixed in latest version.
